<html>
<head>
<title>Welcome to PHP <?php echo PHP_VERSION; ?></title>
<style>
body { font-family: Verdana, Arial, sans-serif; font-size: 13px; background: #fff; color: #000; }
h1 { color: #4F5B93; }
td { font-size: 12px; }
</style>
</head>
<body bgcolor="#ffffff">
<h1>It works! PHP <?php echo PHP_VERSION; ?></h1>
<p>This page was generated by the original PHP <?php echo PHP_VERSION; ?> engine
(Zend Engine <?php echo zend_version(); ?>), compiled to WebAssembly.</p>

<?php
$now = time();
echo "<p>The server time is <b>" . date("l, F jS Y H:i:s T", $now) . "</b>.</p>\n";

$colors = array("#ffffff", "#e8e8f8");
echo "<table border=\"0\" cellpadding=\"3\" cellspacing=\"0\">\n";
echo "<tr bgcolor=\"#9999cc\"><th>n</th><th>n&sup2;</th><th>n!</th><th>fib(n)</th></tr>\n";
function fact($n) { return $n <= 1 ? 1 : $n * fact($n - 1); }
function fib($n) { return $n < 2 ? $n : fib($n - 1) + fib($n - 2); }
for ($i = 1; $i <= 15; $i++) {
    $bg = $colors[$i % 2];
    printf("<tr bgcolor=\"%s\"><td>%d</td><td>%d</td><td>%s</td><td>%d</td></tr>\n",
           $bg, $i, $i * $i, fact($i), fib($i));
}
echo "</table>\n";
?>
<p>Notice <code>14!</code> and <code>15!</code>: integers are 32-bit here, so they
silently overflow into floats, just like on a 2001 i686 Linux box.</p>

<form method="get" action="<?php echo $PHP_SELF; ?>">
What's your name? <input type="text" name="name" value="<?php echo htmlspecialchars(isset($name) ? $name : ''); ?>">
<input type="submit" value="Say hello">
</form>
<?php
// register_globals is On in 4.1.1, so ?name=... becomes $name
if (!empty($name)) {
    echo "<p>Hello, <b>" . htmlspecialchars($name) . "</b>! (via register_globals)</p>";
}
?>
</body>
</html>
