#!/usr/bin/env python3
"""Generate the errno translation layer from two dumps of the same program:
errno_wasm.txt (emscripten: WASI numbering) and errno_linux.txt (i386 glibc,
with strerror() texts). Outputs simphp_errno.h and simphp_errno_table.c."""
import os
here = os.path.dirname(os.path.abspath(__file__))
def load(name):
    vals, msgs = {}, {}
    for line in open(os.path.join(here, name)):
        parts = line.rstrip('\n').split(' ', 2)
        if parts[0] == 'MSG': msgs[int(parts[1])] = parts[2]
        else: vals[parts[0]] = int(parts[1])
    return vals, msgs
wasm, _ = load('errno_wasm.txt')
linux, msgs = load('errno_linux.txt')

h = ['/* Generated by gen_errno.py -- do not edit.',
     ' *',
     ' * Force-included into every PHP 4.1.1 source file (-include). Emscripten',
     ' * numbers errno values the WASI way (ENOENT is 44); PHP prints some of them',
     ' * ("stat failed ... (errno=2 - No such file or directory)", MySQL\'s "(111)",',
     ' * fsockopen()\'s $errno). errno itself and the E* constants stay native so',
     ' * libc and PHP agree; the places that *show* a number use SIMPHP_ERRNO(),',
     ' * and strerror() returns glibc\'s message for the Linux code. */',
     '#ifndef SIMPHP_ERRNO_H', '#define SIMPHP_ERRNO_H', '#include <errno.h>', '#include <string.h>', '',
     'extern int simphp_linux_errno(int wasm_errno);', 'extern char *simphp_strerror(int wasm_errno);',
     '#define SIMPHP_ERRNO(e) simphp_linux_errno(e)', '#define strerror(e) simphp_strerror(e)', '', '#endif', '']
open(os.path.join(here, 'simphp_errno.h'), 'w').write('\n'.join(h))

w2l = {}
for n, v in wasm.items():
    if n in linux: w2l.setdefault(v, linux[n])
maxw = max(w2l) + 1
maxl = max(max(linux.values()), max(msgs)) + 1
l2w = {}
for w, l in w2l.items(): l2w.setdefault(l, w)
c = ['/* Generated by gen_errno.py -- do not edit. */', '',
     f'static const unsigned char simphp_wasm_to_linux[{maxw}] = {{',
     '  ' + ', '.join(str(w2l.get(i, 0) if i else 0) for i in range(maxw)), '};', '',
     f'static const unsigned char simphp_linux_to_wasm[{maxl}] = {{',
     '  ' + ', '.join(str(l2w.get(i, 0) if i else 0) for i in range(maxl)), '};', '',
     f'static const char *const simphp_glibc_errmsg[{maxl}] = {{']
for i in range(maxl):
    m = msgs.get(i, 'Unknown error %d' % i).replace('\\', '\\\\').replace('"', '\\"')
    c.append(f'  "{m}",')
c.append('};')
open(os.path.join(here, 'simphp_errno_table.c'), 'w').write('\n'.join(c) + '\n')
print('names', len(linux), 'wasm codes mapped', len(w2l))
