/* Generated by gen_errno.py -- do not edit.
 *
 * Force-included into every PHP 4.1.1 source file (-include). Emscripten
 * numbers errno values the WASI way (ENOENT is 44); PHP prints some of them
 * ("stat failed ... (errno=2 - No such file or directory)", MySQL's "(111)",
 * fsockopen()'s $errno). errno itself and the E* constants stay native so
 * libc and PHP agree; the places that *show* a number use PHPSIM_ERRNO(),
 * and strerror() returns glibc's message for the Linux code. */
#ifndef PHPSIM_ERRNO_H
#define PHPSIM_ERRNO_H
#include <errno.h>
#include <string.h>

extern int phpsim_linux_errno(int wasm_errno);
extern char *phpsim_strerror(int wasm_errno);
#define PHPSIM_ERRNO(e) phpsim_linux_errno(e)
#define strerror(e) phpsim_strerror(e)

#endif
