/* Generated by gen_errno.py -- do not edit.
 *
 * Force-included into every PHP 4.1.1 source file (-include). Emscripten
 * numbers errno values the WASI way (ENOENT is 44); PHP prints some of them
 * ("stat failed ... (errno=2 - No such file or directory)", MySQL's "(111)",
 * fsockopen()'s $errno). errno itself and the E* constants stay native so
 * libc and PHP agree; the places that *show* a number use SIMPHP_ERRNO(),
 * and strerror() returns glibc's message for the Linux code. */
#ifndef SIMPHP_ERRNO_H
#define SIMPHP_ERRNO_H
#include <errno.h>
#include <string.h>

extern int simphp_linux_errno(int wasm_errno);
extern char *simphp_strerror(int wasm_errno);
#define SIMPHP_ERRNO(e) simphp_linux_errno(e)
#define strerror(e) simphp_strerror(e)

#endif
